<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | ULTI GRAVITY</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            background-color: #f7f9fa;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #fff;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.05);
          }
          h1 {
            color: #0d9488;
            font-size: 28px;
            margin-top: 0;
            font-weight: 700;
            border-bottom: 2px solid #e0f2fe;
            padding-bottom: 12px;
          }
          p {
            font-size: 14px;
            color: #666;
            line-height: 1.6;
          }
          .stats {
            margin: 20px 0;
            padding: 15px;
            background: #f0fdfa;
            border: 1px solid #ccfbf1;
            border-radius: 8px;
            font-size: 14px;
            color: #0f766e;
            font-weight: bold;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            background-color: #f3f4f6;
            color: #374151;
            text-align: left;
            padding: 12px;
            font-weight: 600;
            font-size: 13px;
            border-bottom: 2px solid #e5e7eb;
          }
          td {
            padding: 12px;
            font-size: 13px;
            border-bottom: 1px solid #e5e7eb;
            word-break: break-all;
          }
          tr:hover td {
            background-color: #f5f3ff;
          }
          a {
            color: #2563eb;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .priority-badge {
            display: inline-block;
            padding: 3px 8px;
            background-color: #e0f2fe;
            color: #0369a1;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>XML Sitemap</h1>
          <p>This is a XML Sitemap generated by ULTI GRAVITY for search engines (like Google or Bing) to index the website. You can find more information about XML sitemaps at <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
          
          <div class="stats">
            Total URLs in this sitemap: <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
          </div>

          <table>
            <thead>
              <tr>
                <th style="width: 55%;">URL</th>
                <th style="width: 15%;">Change Freq.</th>
                <th style="width: 15%;">Priority</th>
                <th style="width: 15%;">Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                  </td>
                  <td>
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td>
                    <span class="priority-badge">
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </td>
                  <td style="color: #888;">
                    <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
